[package]
name = "datachannel"
version = "0.1.2"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "Rust wrappers for libdatachannel."
repository = "https://github.com/lerouxrgd/datachannel-rs"
keywords = ["datachannel", "webrtc", "p2p"]
categories = ["network-programming"]
license = "LGPL-2.1"
readme = "README.md"

[dependencies]
datachannel-sys = { path = "datachannel-sys", version = "0.8.0" }
derivative = "2.1"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
webrtc-sdp = "0.3"

[dev-dependencies]
async-channel = "1.1"
# async-std = { version = "1.6", features = ["attributes"] }
async-tungstenite = { version = "0.8", features = ["tokio-runtime"] } # or "async-std-runtime"
crossbeam-channel = "0.4"
env_logger = "0.7"
futures-util = "0.3"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "time"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

[features]
static = ["datachannel-sys/static"]
