[package]
name = "datachannel-sys"
version = "0.8.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
links = "datachannel"
description = "Native bindings to libdatachannel."
repository = "https://github.com/lerouxrgd/datachannel-rs"
categories = ["network-programming"]
license = "LGPL-2.1"

exclude = [
  "libdatachannel/deps/json",
  "libdatachannel/deps/usrsctp/fuzzer",
]

[dependencies]
openssl = "0.10"

[build-dependencies]
bindgen = "0.54"
cmake = "0.1"
cpp_build = { version = "0.5", optional = true }

[features]
static = ["openssl/vendored", "cpp_build"]
